### ISSUE TITLE
Unexpected keyword argument 'config' when in --chat mode

### ISSUE THREAD

**Issue by chz160** [ai-christianson/RA.Aid#127]
Since updating to 17.0, I’ve been receiving the following error when ra.aid first starts up if  use the --chat option. It should be noted that this does not occur when using the -m option instead.

> ╭───────────────────────── Error ────────────────────────────╮
│ Error during research: run_research_agent() got an unexpected keyword argument 'config'      │
╰─────────────────────────────────────────────────────────╯

I attempted to look in the logs to see if there might be a stack trace, however all I found was a DEBUG entry where some error details are being inserted into the trajectory table:
> 2025-03-12 21:31:54,202 - peewee - DEBUG - ('INSERT INTO "trajectory" ("created_at", "updated_at", "human_input_id", "tool_name", "tool_parameters", "tool_result", "step_data", "record_type", "cost", "tokens", "is_error", "error_message", "error_type", "error_details") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [datetime.datetime(2025, 3, 12, 21, 31, 54, 202278), datetime.datetime(2025, 3, 12, 21, 31, 54, 202300), 15, '', None, None, '{"error_message": "Error during research: run_research_agent() got an unexpected keyword argument \'config\'", "display_title": "Error"}', 'error', None, None, True, "Error during research: run_research_agent() got an unexpected keyword argument 'config'", None, None])

**Environment**

- RA.Aid Version: 17.0
- OS: Windows 10 (Running under WSL2 - Ubuntu 22.04)
- Python Version: 3.12.9
- Default Configuration: Yes
- Main Model: anthropic/claude-3-7-sonnet-20250219
- Expert Model: openai/o3-mini

**Steps to Reproduce**

1. Install RA.Aid 17.0 or later.
2. Run the assistant with the default configuration and the --chat option:
    - Main model: anthropic/claude-3-7-sonnet-20250219 @ T1.0
    - Expert model: openai/o3-mini
5. The assistant will immediately throw the unexpected keyword argument 'config' error

If there is something I can do to get you something usable e.g. a stack trace please let me know.

**Comment by ai-christianson** [comment]
Will take a look! 🙂

**Comment by ai-christianson** [comment]
Fixed in v0.17.1: https://github.com/ai-christianson/RA.Aid/releases/tag/v0.17.1
