### ISSUE TITLE
'dict' object has no attribute 'deep_copy'

### ISSUE THREAD

**Issue by ariel-frischer** [ai-christianson/RA.Aid#146]
After merging the latest master branch I've been getting this error immediately after running ra-aid non-chat mode:

```Traceback (most recent call last):
  File "/home/ari/repos/RA.Aid/.venv/bin/ra-aid", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ari/repos/RA.Aid/ra_aid/__main__.py", line 705, in main
    ConfigRepositoryManager(config) as config_repo,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ari/repos/RA.Aid/ra_aid/database/repositories/config_repository.py", line 141, in __enter__
    repo = self.source_repo.deep_copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'deep_copy'
```

I think here is the change:
https://github.com/ai-christianson/RA.Aid/commit/2e9d6a9879eaba03637480aad6c51328f9c47640#diff-2659fee2b4907f6a0061f7ec2c7ff95644c54af11d3f795fe85fdabf3ad50ebcR140
